name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: amanbairagi30/merge-n-share:latest # Replace with your Docker Hub username and repository

      - name: Verify Pushed Image
        run: docker pull amanbairagi30/merge-n-share:latest # Replace with your Docker Hub username and repository

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull amanbairagi30/merge-n-share:latest
            sudo docker stop merged-n-share || true
            sudo docker rm merged-n-share || true
            sudo docker run -d --name merged-n-share -p 3005:3000 amanbairagi30/merge-n-share:latest
